import type { AppConfig } from './config/env';
import { loadConfig } from './config/env';
import { createPool } from './core/plugins/postgres';
import { createRedis } from './core/plugins/redis';
import { runMigrations } from './core/db/migrate';
import { generatePassword } from './core/auth/password';
import { PanelSessions } from './core/auth/session';
import { PanelRepository } from './modules/panel/panel.repository';
import { PANEL_USERNAME_REGEX } from './core/constants';

/**
 * A well-known default is available behind an explicit flag, and it is NOT the default.
 *
 * The tempting argument — "must_change_password blocks every other route, so the window is
 * bounded" — is false, and it fails in the one direction that matters. /auth/password is itself
 * pwExempt (it has to be; it is the route that clears the flag). So an attacker who guesses this
 * BEFORE your first sign-in does not merely read a locked-down panel: they change the password,
 * which revokes every session for that user — and the account is theirs, with you locked out of
 * the break-glass path that re-arms the same race. One request beats a 5-attempt throttle.
 *
 * The panel is internet-facing and the username defaults to 'owner'.
 */
const DEFAULT_PASSWORD = 'owner123';

/**
 * Owner bootstrap and break-glass reset.
 *
 *   npm run panel:owner create [--username <name>] [--password <pw>] [--random]
 *   npm run panel:owner reset --username <name> [--password <pw>] [--random]
 *
 * A CLI rather than a seed-on-boot: server.ts runs buildApp BEFORE runMigrations, so seeding
 * inside a plugin would hit a table that does not exist yet and crash-loop a fresh database.
 * It would also race across CLUSTER_WORKERS.
 *
 * The password is GENERATED and printed once, never read from an env var: PANEL_OWNER_PASSWORD
 * would sit in .env forever, and rotating it there would silently do nothing.
 *
 * `reset` is not optional — it is the only way back in. There is no email, no self-serve
 * reset, and the sole owner cannot ask anyone else to reset them.
 */
async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0] ?? 'create';
  const usernameFlag = args.indexOf('--username');
  const username = usernameFlag >= 0 ? args[usernameFlag + 1] : undefined;
  const passwordFlag = args.indexOf('--password');
  const explicitPassword = passwordFlag >= 0 ? args[passwordFlag + 1] : undefined;

  if (command !== 'create' && command !== 'reset') {
    console.error('usage: panel-owner [create|reset] [--username <name>] [--password <pw>|--easy]');
    console.error('  default: a generated password, printed once');
    console.error('  --easy:  the well-known "owner123" — only if you are signing in right now');
    process.exit(2);
  }
  if (explicitPassword !== undefined && explicitPassword.length < 6) {
    console.error('--password must be at least 6 characters.');
    process.exit(2);
  }
  if (username !== undefined && !PANEL_USERNAME_REGEX.test(username)) {
    console.error(`Invalid username. Must match ${PANEL_USERNAME_REGEX}`);
    process.exit(2);
  }

  // createPool, never `new Pool({connectionString, password})`: node-postgres merges the
  // connection string OVER the rest of the config, so a password embedded in DATABASE_URL
  // silently wins and the PGPASSWORD_FILE secret is discarded. That is the exact bug
  // core/plugins/postgres.ts exists to prevent — and this CLI is where it hurts most, since
  // `reset` is the only way back into a locked-out panel.
  const config = loadConfig();
  const pool = createPool(config);

  try {
    // Safe to re-run, and it means `panel:owner` works on a database that has never booted the
    // API — which is exactly the situation you are in the first time.
    await runMigrations(pool, () => {});
    const repo = new PanelRepository(pool);

    // Generated by default. --easy opts into the well-known password when you are about to sign
    // in immediately and want to skip the copy-paste; see DEFAULT_PASSWORD for why that is a
    // race and not merely "a bounded window".
    const password = args.includes('--easy') ? DEFAULT_PASSWORD : (explicitPassword ?? generatePassword());
    const isWellKnown = password === DEFAULT_PASSWORD;

    if (command === 'create') {
      const existing = await repo.countOwners();
      if (existing > 0 && !username) {
        // Idempotent: re-running the bootstrap must not mint a second owner or reset the first.
        console.log(`An owner already exists. Nothing to do.`);
        console.log(`(To add another account, use the panel. To reset a password: panel:owner reset --username <name>)`);
        return;
      }
      const name = username ?? 'owner';
      const user = await repo.create(name, password, 'owner', null);
      print(user.username, password, 'created', isWellKnown);
    } else {
      if (!username) {
        console.error('reset requires --username <name>');
        process.exit(2);
      }
      const user = await repo.findForAuth(username);
      if (!user) {
        console.error(`No account named ${username}.`);
        process.exit(1);
      }
      await repo.resetPassword(user.userId, password);
      // A password reset that leaves the attacker's session alive and the owner locked out is
      // not a recovery — it is the exact hole a stolen-cookie + login-flood chain rides through.
      // So the break-glass path also evicts every live session and clears the per-username login
      // bucket. Best-effort: the password is already changed in Postgres, and "the only way back
      // in" must not fail just because Redis is down.
      await revokeAndUnlock(config, user.userId, user.username);
      print(user.username, password, 'reset', isWellKnown);
    }
  } finally {
    await pool.end();
  }
}

/**
 * Evict every live session for the reset account and clear its per-username login bucket.
 *
 * revokeAll bumps the generation counter, so a stolen cookie stops resolving the instant this
 * runs. Clearing `pl:u:<name>` un-sticks the owner's own login — a flood of bad passwords fills
 * that bucket, and nothing else here would reset it. Both are best-effort: a Redis outage prints
 * a warning rather than failing the reset, since the password change already landed in Postgres.
 */
async function revokeAndUnlock(config: AppConfig, userId: string, username: string): Promise<void> {
  const redis = createRedis(config);
  try {
    const sessions = new PanelSessions(
      redis,
      config.env.REDIS_KEY_PREFIX,
      config.env.PANEL_SESSION_IDLE_MINUTES * 60,
      config.env.PANEL_SESSION_ABSOLUTE_HOURS * 3600,
    );
    await sessions.revokeAll(userId);
    // Same key shape as loginBuckets() in modules/panel/login-throttle.ts.
    await redis.del(`${config.env.REDIS_KEY_PREFIX}pl:u:${username.toLowerCase()}`);
  } catch (err) {
    console.warn(
      `  ! Could not reach Redis to revoke sessions / clear the login lock: ${
        err instanceof Error ? err.message : err
      }`,
    );
    console.warn('    The password is reset, but a stolen session may persist until Redis is back.');
  } finally {
    redis.disconnect();
  }
}

function print(username: string, password: string, what: string, isWellKnown: boolean): void {
  console.log('');
  console.log(`  Owner account ${what}.`);
  console.log('');
  console.log(`    username: ${username}`);
  console.log(`    password: ${password}`);
  console.log('');
  if (isWellKnown) {
    // Not a formality, and not merely "change it soon": whoever signs in first WINS the account,
    // because /auth/password is reachable while must_change_password is set and it revokes every
    // other session for the user. Sign in now, from this terminal.
    console.log('  ** Well-known password. Sign in RIGHT NOW and change it. **');
    console.log('  Whoever signs in first owns this account — they can change the password too,');
    console.log('  and that locks you out. Re-run without --easy for a generated one.');
  } else {
    console.log('  Shown once — it is not recoverable. Sign in and you will be asked to change it.');
  }
  console.log('');
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
